import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * Convex schema definition for HypeShelf
 *
 * Recommendations table stores all movie/show recommendations
 * Users table (optional) stores role information for access control
 */
export default defineSchema({
  recommendations: defineTable({
    // Required fields
    title: v.string(),
    genre: v.string(), // e.g., "horror", "action", "comedy", etc.
    link: v.string(), // URL to the movie/show
    blurb: v.string(), // Short description
    authorId: v.string(), // Clerk user ID
    authorName: v.string(), // User's display name
    isStaffPick: v.boolean(), // Marked by admin as staff pick
    // Note: _id and _creationTime are auto-generated by Convex
  })
    .index("by_author", ["authorId"])
    .index("by_genre", ["genre"])
    .index("by_staff_pick", ["isStaffPick"]),

  // Optional: Users table for role management
  // Alternative: Roles can be stored in Clerk's public metadata (current approach)
  users: defineTable({
    clerkUserId: v.string(), // Clerk user ID (unique identifier)
    role: v.union(v.literal("admin"), v.literal("user")), // User role
    email: v.string(), // User email
    // Note: _id and _creationTime are auto-generated by Convex
  }).index("by_clerk_user_id", ["clerkUserId"]),
});
